/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;

import controller.ProjectController;
import controller.TaskController;
import java.sql.Connection;
import java.util.Date;
import java.util.List;
import model.Project;
import model.Task;
import util.ConnectionFactory;

public class App {
    

    public static void main(String[] args) {
       
//        Connection c = ConnectionFactory.getConnection();
//        
//        ConnectionFactory.closeConnection(c);
        

//        ProjectController projectController = new ProjectController();
//        
//        Project project = new Project();
//        project.setName("Projeto teste");
//        project.setDescription("description");
//        projectController.save(project);
        
        
//        ProjectController projectController = new ProjectController();
//        
//        Project project = new Project();
//        project.setId(1);
//        project.setName("Novo nome do projeto novamente");
//        project.setDescription("description");
//        
//        
//        projectController.update(project);
//        
//        List<Project> projects = projectController.getAll();
//        System.out.println("Total de projetos = " + projects.size());
//        
//        projectController.removeById(1);
        
          TaskController taskController = new TaskController();
//        
      Task task = new Task();
      task.setIdProject(2);
      task.setId(4);
      task.setName("MUDAR as telas da aplicação");
//      task.setDescription("cadastros");
//      task.setNotes("Sem notas");
//      task.setIsCompleted(false);
//      task.setDeadline(new Date());
        
        taskController.update(task);
        
//        List<Task> tasks = taskController.getAll(2);
//        System.out.println("Total de tarefas " + tasks.size());
        
        

    }
}
